### ISSUE TITLE
error when using the stats button

### ISSUE THREAD

**Issue by Heisii** [harbassan/spicetify-apps#165]
so uhh guys is this normal or am i just not using my brain right

![image_2024-11-26_015014674](https://github.com/user-attachments/assets/34f20eb5-8dba-4725-8965-1bc4412b9483)

**Comment by sayanoops** [comment]
its happening with me too

**Comment by amolinarius** [comment]
Same issue here

**Comment by 1ightmare** [comment]
Follow the manual installation guide in readme. Down i'm basically rephrasing it. Also i didn't uninstall anything before doing these steps.
1. Manually download the latest release
2. Open spicetify directory (u can simply paste the path in Run (W+R for windows, don't know the shortcut for linux/macos)
For Windows                `%appdata%\spicetify\CustomApps\`
For Linux/MacOS         `~/.config/spicetify/CustomApps)`
3. Extract the zip file here, in CustomApps directory
4. Run these lines in the CLI
```
spicetify config custom_apps <file name>
spicetify apply
```
5. It should work now

**Comment by raffarevv1** [comment]
![Screenshot 2024-12-31 031157](https://github.com/user-attachments/assets/e55f0f69-7b97-4801-89e4-0b0cad268cd5)
I still have the same issues
